services:
  postgres:
    container_name: 'olympos-postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=olympos'
      - 'POSTGRES_PASSWORD=olympos_secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
